/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author teewa743
 */
public class MainMenu extends javax.swing.JFrame {
final dao.ProductDAO productsList;
	/**
	 * Creates new form MainMenu
	 */
	public MainMenu(dao.ProductDAO productsList) {
		this.productsList = productsList;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      addProductButton = new javax.swing.JButton();
      viewProductButton = new javax.swing.JButton();
      exitButton = new javax.swing.JButton();
      label1 = new java.awt.Label();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      addProductButton.setText("Add a New Product");
      addProductButton.setName("addProductButton"); // NOI18N
      addProductButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addProductButtonActionPerformed(evt);
         }
      });

      viewProductButton.setText("View Products");
      viewProductButton.setName("viewProductButton"); // NOI18N
      viewProductButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            viewProductButtonActionPerformed(evt);
         }
      });

      exitButton.setText("Exit");
      exitButton.setName("exitButton"); // NOI18N
      exitButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitButtonActionPerformed(evt);
         }
      });

      label1.setName(""); // NOI18N
      label1.setText("Product Administration");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(102, 102, 102)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(addProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                  .addComponent(viewProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap(82, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(addProductButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(viewProductButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(exitButton)
            .addContainerGap(87, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
      ProductEditor productEditor = new ProductEditor(this, true, productsList);
		productEditor.setLocationRelativeTo(this);
		productEditor.setVisible(true);
   }//GEN-LAST:event_addProductButtonActionPerformed

   private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
     System.exit(0);
   }//GEN-LAST:event_exitButtonActionPerformed

   private void viewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductButtonActionPerformed
   ViewProduct viewproduct = new ViewProduct(this, true, productsList);
	viewproduct.setLocationRelativeTo(this);
	viewproduct.setVisible(true);
   }//GEN-LAST:event_viewProductButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton addProductButton;
   private javax.swing.JButton exitButton;
   private java.awt.Label label1;
   private javax.swing.JButton viewProductButton;
   // End of variables declaration//GEN-END:variables
}
