/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.math.BigDecimal;

/**
 *
 * @author teewa743
 */
public class ProductEditor extends javax.swing.JDialog {

	/**
	 * Creates new form ProductEditor
	 */
	public ProductEditor(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		categorycombobox.setEditable(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      productID = new javax.swing.JLabel();
      productName = new javax.swing.JLabel();
      productDescription = new javax.swing.JLabel();
      productCategory = new javax.swing.JLabel();
      productPrice = new javax.swing.JLabel();
      productQuantity = new javax.swing.JLabel();
      txtId = new javax.swing.JTextField();
      txtName = new javax.swing.JTextField();
      scrollDescription = new javax.swing.JScrollPane();
      txtDescription = new javax.swing.JTextArea();
      txtPrice = new javax.swing.JTextField();
      txtQuantity = new javax.swing.JTextField();
      saveButton = new javax.swing.JButton();
      cancelButton = new javax.swing.JButton();
      categorycombobox = new javax.swing.JComboBox<>();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      productID.setText("ID:");
      productID.setName("productID"); // NOI18N

      productName.setText("Name:");
      productName.setName("productName"); // NOI18N

      productDescription.setText("Desciption:");
      productDescription.setName("productDescription"); // NOI18N

      productCategory.setText("Category:");
      productCategory.setName("productCategory"); // NOI18N

      productPrice.setText("Price:");
      productPrice.setName("productPrice"); // NOI18N

      productQuantity.setText("Quantity in Stock:");
      productQuantity.setName("productQuantity"); // NOI18N

      txtId.setName("txtId"); // NOI18N

      txtName.setName("txtName"); // NOI18N

      scrollDescription.setName("scrollDescription"); // NOI18N

      txtDescription.setColumns(20);
      txtDescription.setRows(5);
      txtDescription.setName("txtDescription"); // NOI18N
      scrollDescription.setViewportView(txtDescription);

      txtPrice.setName("txtPrice"); // NOI18N

      txtQuantity.setName("txtQuantity"); // NOI18N

      saveButton.setText("Save");
      saveButton.setName("saveButton"); // NOI18N
      saveButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveButtonActionPerformed(evt);
         }
      });

      cancelButton.setText("Cancel");
      cancelButton.setName("cancelButton"); // NOI18N
      cancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelButtonActionPerformed(evt);
         }
      });

      categorycombobox.setName("categorycombobox"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(productID, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(productName, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(productDescription, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(productCategory, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(productPrice, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(productQuantity, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtId)
               .addComponent(txtName)
               .addComponent(scrollDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
               .addComponent(txtPrice)
               .addComponent(txtQuantity)
               .addComponent(categorycombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGap(96, 96, 96)
            .addComponent(saveButton)
            .addGap(38, 38, 38)
            .addComponent(cancelButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(productID)
               .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(productName)
               .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(productDescription)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addComponent(scrollDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(productCategory)
               .addComponent(categorycombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(15, 15, 15)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(productPrice)
               .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(productQuantity)
               .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(saveButton)
               .addComponent(cancelButton)))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		String id = txtId.getText();
		String name = txtName.getText();
		String description = txtDescription.getText();
		String category = (String) categorycombobox.getSelectedItem();
		String price = txtPrice.getText();
		String quantity = txtQuantity.getText();
		BigDecimal p = new BigDecimal(price);
		BigDecimal q = new BigDecimal(quantity);
		domain.Product product = new domain.Product();
		product.setProduct_id(id);
		product.setList_price(p);
		product.setName(name);
		product.setCategory(category);
		product.setDescription(description);
		product.setQuantity_in_stock(q);
   }//GEN-LAST:event_saveButtonActionPerformed

   private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
      dispose();
   }//GEN-LAST:event_cancelButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProductEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProductEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProductEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProductEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ProductEditor dialog = new ProductEditor(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton cancelButton;
   private javax.swing.JComboBox<String> categorycombobox;
   private javax.swing.JLabel productCategory;
   private javax.swing.JLabel productDescription;
   private javax.swing.JLabel productID;
   private javax.swing.JLabel productName;
   private javax.swing.JLabel productPrice;
   private javax.swing.JLabel productQuantity;
   private javax.swing.JButton saveButton;
   private javax.swing.JScrollPane scrollDescription;
   private javax.swing.JTextArea txtDescription;
   private javax.swing.JTextField txtId;
   private javax.swing.JTextField txtName;
   private javax.swing.JTextField txtPrice;
   private javax.swing.JTextField txtQuantity;
   // End of variables declaration//GEN-END:variables
}
