@startuml
skinparam {
  Style StrictUML
  SequenceStereotype {
    Font {
      Size 10
      Style plain
    }
  }
}
actor "User" as user
participant "MainMenu" as menu <<gui>>
participant "ProductEditor" as productEditor <<gui>>
participant "product: Product" as product <<domain>>
participant "productsList: ProductCollectionsDAO" as ProductCollectionsDAO <<dao>>
participant "categoriesModel: SimpleListModel" as SimpleListModel <<helpers>>


'create the product editor menu
' user clicks the view a product button
user -> menu++ : clicks the "Add a product" button
create productEditor
menu -> productEditor : <<construct>>

user -> productEditor++ : Enter product details
create ProductCollectionsDAO
productEditor -> ProductCollectionsDAO : <<construct>>
create SimpleListModel
productEditor -> SimpleListModel : <<construct>>
productEditor--

productEditor -> ProductCollectionsDAO++ :getCategories()
productEditor++
ProductCollectionsDAO --> productEditor :categories
ProductCollectionsDAO--
productEditor -> SimpleListModel++:updateItems(categories);
SimpleListModel--
productEditor -> productEditor :setModel(productsModel);
productEditor--

user -> productEditor++ : Clicks "save" button
productEditor --> productEditor: getText()
productEditor --> productEditor: getSelectedItem()
create product
productEditor -> product: <<construct>>
'user enter variables
productEditor -> product++ :set variables 
product--

productEditor -> ProductCollectionsDAO++ : saveProduct(product)
ProductCollectionsDAO--
productEditor -> productEditor :dispose();
destroy productEditor 
productEditor --> menu

@enduml
